version: '3.9'
volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    container_name: postgres_broker
    image: postgres:11.13-alpine
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=50'
      - '-c'
      - 'shared_buffers=1GB'
      - '-c'
      - 'effective_cache_size=4GB'
      - '-c'
      - 'work_mem=16MB'
      - '-c'
      - 'maintenance_work_mem=512MB'
      - '-c'
      - 'random_page_cost=1.1'
      - '-c'
      - 'temp_file_limit=10GB'
      - '-c'
      - 'log_min_duration_statement=200ms'
      - '-c'
      - 'idle_in_transaction_session_timeout=10s'
      - '-c'
      - 'lock_timeout=1s'
      - '-c'
      - 'statement_timeout=60s'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.max=10000'
      - '-c'
      - 'pg_stat_statements.track=all'
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-broker_db}
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASS:-user}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/core:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER:-user} -d ${DATABASE_NAME:-broker_db}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      broker:
        ipv4_address: 171.4.4.11
        aliases:
          - postgres.broker.loc
  
  redis:
    container_name: redis_broker
    image: redis
    ports: 
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-pass}
    volumes: 
      - redis_data:/data
    networks:
      broker:
        ipv4_address: 171.4.4.14
        aliases:
          - redis.broker.loc

  rabbitmq:
    container_name: rabbitmq-broker
    build:
      context: ./
      dockerfile: ./docker/rabbitmq.dockerfile
    image: rabbitmq:docker
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASS:-pass}
    ports:
      - 443:443
      - 1883:1883
      - 5672:5672
      - 15672:15672
      - 15675:15675
    networks:
      broker:
        ipv4_address: 171.4.4.20
        aliases:
          - broker.rabbitmq.loc

  frontend:
    hostname: "broker-frontend"
    build:
      context: ./
      dockerfile: docker/frontend.dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 3000:80
    networks:
      broker:
        ipv4_address: 171.4.4.13
        aliases:
          - broker.api.frontend.loc

  broker-core:
    container_name: broker-core
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - broker-smtp
    build:
      context: .
      dockerfile: ./docker/core.dockerfile
    ports:
     - ${PORT:-8080}:80
    command: 
      ["./wait-for-it.sh", "5432"]
    env_file:
      - ./services/core/.env
    networks:
      broker:
        ipv4_address: 171.4.4.12
        aliases:
          - core.broker.loc  

  broker-smtp:
    container_name: broker-smtp
    build:
      context: .
      dockerfile: ./docker/smtp.dockerfile
    ports:
     - ${PORT:-8081}:80
    env_file:
      - ./services/smtp/.env
    networks:
      broker:
        ipv4_address: 171.4.4.17
        aliases:
          - smtp.broker.loc    

networks:
  broker:
    name: broker
    ipam:
      config:
        - subnet: "171.4.4.0/24"